/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ig;

import javax.swing.JOptionPane;
import persistencia.Conexao;

/**
 *
 * @author bigma
 */
public class CriarConta extends javax.swing.JPanel {

    IGbatalha painelPrincipal;
    public CriarConta(IGbatalha painelPrincipal) {
        this.painelPrincipal = painelPrincipal;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        novoUsuario = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        novaSenha = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        confirmaSenha = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btnVoltar = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(500, 500));
        setPreferredSize(new java.awt.Dimension(500, 500));
        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Digite seu usuário:");
        add(jLabel1);
        jLabel1.setBounds(160, 120, 180, 25);
        add(novoUsuario);
        novoUsuario.setBounds(160, 150, 180, 22);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Digite sua senha:");
        add(jLabel2);
        jLabel2.setBounds(150, 180, 190, 25);
        add(novaSenha);
        novaSenha.setBounds(160, 210, 180, 22);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Confirme sua senha:");
        add(jLabel3);
        jLabel3.setBounds(160, 240, 180, 25);
        add(confirmaSenha);
        confirmaSenha.setBounds(160, 280, 180, 22);

        jButton1.setBackground(new java.awt.Color(0, 0, 153));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Criar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1);
        jButton1.setBounds(150, 330, 200, 40);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Batalha Naval");
        add(jLabel4);
        jLabel4.setBounds(130, 20, 230, 32);

        btnVoltar.setBackground(new java.awt.Color(0, 0, 153));
        btnVoltar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnVoltar.setForeground(new java.awt.Color(255, 255, 255));
        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });
        add(btnVoltar);
        btnVoltar.setBounds(150, 380, 200, 40);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        String usuario = novoUsuario.getText();
        String senha = novaSenha.getText();
        String confirma_senha = confirmaSenha.getText();
        
        if(senha.equals(confirma_senha)){
          if (Conexao.cadastrarConta(usuario, senha) > 0) {
                JOptionPane.showMessageDialog(null, "Cadastro feito com sucesso!");
                painelPrincipal.trocarPainel(new TelaInicio(this.painelPrincipal), 500,500);               
            } else {
                JOptionPane.showMessageDialog(null, "Não foi possivel cadastrar.");
            }
          
        }else{
          JOptionPane.showMessageDialog(null, "As senhas precisam ser iguais.");   
        }
        
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        this.painelPrincipal.trocarPainel(new TelaInicio(this.painelPrincipal),500,500);
    }//GEN-LAST:event_btnVoltarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVoltar;
    private javax.swing.JTextField confirmaSenha;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField novaSenha;
    private javax.swing.JTextField novoUsuario;
    // End of variables declaration//GEN-END:variables
}
