/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ig;

/**
 *
 * @author bigma
 */
public class Lobby extends javax.swing.JPanel {

    IGbatalha painelPrincipal;
    String nome_jogador1;
    public Lobby(IGbatalha painelPrincipal, String nome_jogador) {
        this.painelPrincipal = painelPrincipal;
        this.nome_jogador1 = nome_jogador;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnIniciaJogo = new javax.swing.JButton();
        nomeJogador2 = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(500, 500));
        setPreferredSize(new java.awt.Dimension(500, 500));
        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Lobby");
        add(jLabel1);
        jLabel1.setBounds(170, 30, 170, 32);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Digite o nome do oponente:");
        add(jLabel2);
        jLabel2.setBounds(120, 160, 260, 25);

        btnIniciaJogo.setBackground(new java.awt.Color(0, 0, 153));
        btnIniciaJogo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnIniciaJogo.setForeground(new java.awt.Color(255, 255, 255));
        btnIniciaJogo.setText("Jogar");
        btnIniciaJogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciaJogoActionPerformed(evt);
            }
        });
        add(btnIniciaJogo);
        btnIniciaJogo.setBounds(170, 370, 170, 50);
        add(nomeJogador2);
        nomeJogador2.setBounds(120, 230, 260, 40);
    }// </editor-fold>//GEN-END:initComponents

    private void btnIniciaJogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciaJogoActionPerformed
        String nome_jogador2 = nomeJogador2.getText();
        this.painelPrincipal.trocarPainel(new TelaJogo(this.painelPrincipal, nome_jogador1, nome_jogador2), 1018, 598);
    }//GEN-LAST:event_btnIniciaJogoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIniciaJogo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField nomeJogador2;
    // End of variables declaration//GEN-END:variables
}
